### ISSUE TITLE
[Feat] 특정 메뉴 목록 조회

### ISSUE THREAD

**Issue by soyuul** [JPA-study-project/jpa-project#3]
# 기능 추가/수정 요청

## 기능 설명
메뉴 코드를 이용한 특정 메뉴 조회

## 기대하는 효과
특정 메뉴만을 조회할 수 있다

## 구현 가능성
findById 메소드 사용

## TO-DO
- [ ] MenuController에 GET / POST 추가
- [ ] MenuService에 특정 메뉴 조회를 위한 비즈니스 로직 추가
- [x] MenuRepository에 관련 메소드 작성
