### ISSUE TITLE
[Feat] 메뉴 추가

### ISSUE THREAD

**Issue by soyuul** [JPA-study-project/jpa-project#5]
# 기능 추가/수정 요청

## 기능 설명
메뉴 추가

## 기대하는 효과
메뉴를 추가할 수 있다

## 구현 가능성
JPA이용 fetch사용

## TO-DO
- [ ]  MenuController에 메뉴 전체 조회 GET 추가
- [ ]  MenuService에 엔티티 저장
- [x]  MenuRepository에 관련 메소드 작성
